version: "2"
run:
  timeout: 5m
linters:
  enable:
    - gosec          # SAST security
    - errcheck       # erreurs jamais ignorées
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
  settings:
    gosec:
      severity: medium
      confidence: medium
  exclusions:
    rules:
      - path: _test\.go
        linters: [errcheck]
      - path: _test\.go
        linters: [gosec]
